package main

import (
	"fmt"
	"strings"

	"github.com/GiGurra/q/pkg/q"
)

// Phase 4.1 fixture: q.AtCompileTimeCode — closure returns Go source
// code; the rewriter splices the parsed expression at the call site.
// This is the macro flavour: code is generated at preprocessor time,
// then compiled like any hand-written code.

func main() {
	// 1. A function literal generated as text. The closure builds a
	//    `func(string) string` body whose contents are themselves
	//    determined at preprocessor time (here a literal greeting).
	greet := q.AtCompileTimeCode[func(string) string](func() string {
		return `func(name string) string { return "Hello, " + name }`
	})
	fmt.Println(greet("alice"))
	fmt.Println(greet("bob"))

	// 2. A constant-style expression — string literal generated by
	//    walking some preprocessor-time data.
	tag := q.AtCompileTimeCode[string](func() string {
		parts := []string{"prod", "edge", "v2"}
		return strings.Join([]string{`"`, strings.Join(parts, "-"), `"`}, "")
	})
	fmt.Println("tag:", tag)

	// 3. A larger function value — switch over comptime-computed
	//    cases. Demonstrates that the spliced expression can be a
	//    multi-line function literal.
	classify := q.AtCompileTimeCode[func(int) string](func() string {
		var b strings.Builder
		b.WriteString("func(n int) string {\n")
		b.WriteString("\tswitch {\n")
		b.WriteString("\tcase n < 0:\n\t\treturn \"negative\"\n")
		b.WriteString("\tcase n == 0:\n\t\treturn \"zero\"\n")
		b.WriteString("\tcase n < 10:\n\t\treturn \"small\"\n")
		b.WriteString("\tdefault:\n\t\treturn \"large\"\n")
		b.WriteString("\t}\n")
		b.WriteString("}")
		return b.String()
	})
	fmt.Println("classify(-5):", classify(-5))
	fmt.Println("classify(0):", classify(0))
	fmt.Println("classify(5):", classify(5))
	fmt.Println("classify(100):", classify(100))
}
