package preprocessor

// gen.go — file-synthesis pass for the q.Gen* directives. After the
// scanner detects `var _ = q.GenStringer[T]()` (and friends) at
// package scope, this pass collects the directives across all files
// in the user's package, generates a single companion file
// containing the requested method declarations, and appends the
// file to the compile argv.
//
// One companion file per compile unit (not per directive) so the
// imports + package clause are written once. The file is named
// `_q_gen.go` for clarity in stack traces / DWARF, though it
// actually lives in $TMPDIR.

import (
	"fmt"
	"go/token"
	"sort"
	"strconv"
	"strings"
)

// genDirective is one resolved Gen* call. For familySealed, typeName
// is the marker interface's name, sealedMarker is the marker method
// name, and sealedVariants is the per-variant type spelling (each one
// gets a synthesised `func (V) markerMethod() {}` body).
type genDirective struct {
	family         family
	typeName       string
	constNames     []string
	constValues    []string
	underlying     string
	pos            token.Position
	sealedMarker   string
	sealedVariants []string
}

// collectGenDirectives walks all shapes in a package compile and
// returns the resolved Gen* directives in deterministic order.
// Unresolved directives (typecheck couldn't run, or the type
// produced a diagnostic) are skipped — those errors surface
// separately via the diagnostics path.
func collectGenDirectives(fset *token.FileSet, shapes []callShape) []genDirective {
	var dirs []genDirective
	for _, sh := range shapes {
		for _, sc := range sh.Calls {
			switch sc.Family {
			case familyGenStringer, familyGenEnumJSONStrict, familyGenEnumJSONLax:
				if sc.EnumTypeText == "" || len(sc.EnumConsts) == 0 {
					continue
				}
				dirs = append(dirs, genDirective{
					family:      sc.Family,
					typeName:    sc.EnumTypeText,
					constNames:  sc.EnumConsts,
					constValues: sc.EnumConstValues,
					underlying:  sc.EnumUnderlyingKind,
					pos:         fset.Position(sc.OuterCall.Pos()),
				})
			case familySealed:
				if sc.SealedMarkerName == "" || len(sc.SealedVariantNames) == 0 {
					continue
				}
				// typeName here doubles as a stable key for dedup —
				// use the marker method name, which is unique per
				// marker interface within a package (interfaces
				// share methods via embedding, not naming).
				dirs = append(dirs, genDirective{
					family:         sc.Family,
					typeName:       sc.SealedMarkerName,
					sealedMarker:   sc.SealedMarkerName,
					sealedVariants: sc.SealedVariantNames,
					pos:            fset.Position(sc.OuterCall.Pos()),
				})
			default:
				continue
			}
		}
	}
	// Stable ordering: by family then type name. Multiple directives
	// of the same family on the same type collapse to the first one
	// (later duplicates would generate duplicate methods, which the
	// Go compiler would reject anyway).
	sort.SliceStable(dirs, func(i, j int) bool {
		if dirs[i].family != dirs[j].family {
			return dirs[i].family < dirs[j].family
		}
		return dirs[i].typeName < dirs[j].typeName
	})
	dirs = dedupeGenDirectives(dirs)
	return dirs
}

// dedupeGenDirectives drops repeats of the same (family, typeName)
// pair, keeping the first occurrence in the sorted order.
func dedupeGenDirectives(dirs []genDirective) []genDirective {
	seen := map[string]bool{}
	out := dirs[:0]
	for _, d := range dirs {
		key := fmt.Sprintf("%d/%s", d.family, d.typeName)
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, d)
	}
	return out
}

// synthesizeGenFile produces the source text for the companion
// methods file. pkgName is the user package's name (so the synthetic
// file can declare `package <pkgName>`). Returns ("", nil) when
// there are no directives.
func synthesizeGenFile(pkgName string, dirs []genDirective) string {
	if len(dirs) == 0 {
		return ""
	}
	var imports []string
	importSet := map[string]bool{}
	addImport := func(p string) {
		if !importSet[p] {
			importSet[p] = true
			imports = append(imports, p)
		}
	}

	var bodies []string
	for _, d := range dirs {
		switch d.family {
		case familyGenStringer:
			bodies = append(bodies, generateStringerMethod(d))
		case familyGenEnumJSONStrict:
			addImport("encoding/json")
			addImport("fmt")
			bodies = append(bodies, generateJSONStrictMethods(d))
		case familyGenEnumJSONLax:
			addImport("encoding/json")
			bodies = append(bodies, generateJSONLaxMethods(d))
		case familySealed:
			bodies = append(bodies, generateSealedMarkerMethods(d))
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by the q preprocessor. DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkgName)
	b.WriteString("\n\n")
	if len(imports) > 0 {
		sort.Strings(imports)
		b.WriteString("import (\n")
		for _, p := range imports {
			b.WriteString("\t")
			b.WriteString(strconv.Quote(p))
			b.WriteString("\n")
		}
		b.WriteString(")\n\n")
	}
	for _, body := range bodies {
		b.WriteString(body)
		b.WriteString("\n")
	}
	return b.String()
}

// generateStringerMethod emits `func (v T) String() string` for the
// directive. The body is an inline switch over the constants — same
// shape q.EnumName produces, but as a real method on T.
func generateStringerMethod(d genDirective) string {
	var b strings.Builder
	fmt.Fprintf(&b, "func (v %s) String() string {\n", d.typeName)
	b.WriteString("\tswitch v {\n")
	for _, name := range d.constNames {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %q\n", name, name)
	}
	b.WriteString("\t}\n\treturn \"\"\n}\n")
	return b.String()
}

// generateJSONStrictMethods emits MarshalJSON / UnmarshalJSON that
// use the constant names as the wire format and error on unknown
// values. Compatible with q.Exhaustive — every successfully-
// unmarshalled value is a declared constant.
func generateJSONStrictMethods(d genDirective) string {
	var b strings.Builder
	// Marshal: switch on value, emit name.
	fmt.Fprintf(&b, "func (v %s) MarshalJSON() ([]byte, error) {\n", d.typeName)
	b.WriteString("\tswitch v {\n")
	for _, name := range d.constNames {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn []byte(%q), nil\n", name, strconv.Quote(name))
	}
	fmt.Fprintf(&b, "\t}\n\treturn nil, fmt.Errorf(\"q.GenEnumJSONStrict[%s]: unknown value %%v\", v)\n}\n", d.typeName)

	// Unmarshal: parse string, look up by name, error on unknown.
	fmt.Fprintf(&b, "\nfunc (v *%s) UnmarshalJSON(b []byte) error {\n", d.typeName)
	b.WriteString("\tvar s string\n")
	b.WriteString("\tif err := json.Unmarshal(b, &s); err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn fmt.Errorf(\"q.GenEnumJSONStrict[%s]: %%w\", err)\n", d.typeName)
	b.WriteString("\t}\n")
	b.WriteString("\tswitch s {\n")
	for _, name := range d.constNames {
		fmt.Fprintf(&b, "\tcase %q:\n\t\t*v = %s\n\t\treturn nil\n", name, name)
	}
	fmt.Fprintf(&b, "\t}\n\treturn fmt.Errorf(\"q.GenEnumJSONStrict[%s]: unknown name %%q\", s)\n}\n", d.typeName)
	return b.String()
}

// generateSealedMarkerMethods emits one
//
//	func (V) markerMethod() {}
//
// per variant in the q.Sealed directive — so each variant satisfies
// the marker interface via the synthesised method. Same-package
// declaration is enforced by the typecheck pass; this code assumes
// the variants live in the user's package.
func generateSealedMarkerMethods(d genDirective) string {
	var b strings.Builder
	for _, v := range d.sealedVariants {
		fmt.Fprintf(&b, "func (%s) %s() {}\n", v, d.sealedMarker)
	}
	return b.String()
}

// generateJSONLaxMethods emits MarshalJSON / UnmarshalJSON that
// pass through the underlying type. Any value (known or not) is
// accepted on unmarshal, preserving wire drift for forward-compat.
//
// For string-backed: emit / accept the underlying string verbatim.
// For int-backed (and other numerics): emit / accept the underlying
// numeric value.
func generateJSONLaxMethods(d genDirective) string {
	var b strings.Builder
	uType := d.underlying
	if uType == "" {
		// Underlying not resolved — fall back to no-op methods
		// that compile but don't transform. Should be rare; the
		// typecheck pass would have surfaced the missing type info.
		uType = "any"
	}
	// Marshal: cast to underlying, defer to json.Marshal.
	fmt.Fprintf(&b, "func (v %s) MarshalJSON() ([]byte, error) {\n", d.typeName)
	fmt.Fprintf(&b, "\treturn json.Marshal(%s(v))\n", uType)
	b.WriteString("}\n")
	// Unmarshal: parse to underlying, cast back.
	fmt.Fprintf(&b, "\nfunc (v *%s) UnmarshalJSON(b []byte) error {\n", d.typeName)
	fmt.Fprintf(&b, "\tvar raw %s\n", uType)
	b.WriteString("\tif err := json.Unmarshal(b, &raw); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\t*v = %s(raw)\n", d.typeName)
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
	return b.String()
}
