package preprocessor

// Phase 1b handler: augment the standard library `runtime` package's
// compile with a synthesized Go file that exports a tiny accessor for
// g.goid. Without this, pkg/q's GoroutineID wrapper fails to link.
//
// The runtime package is special-cased only in dispatch — once a
// source file is added to its compile argv, the Go compiler treats it
// like any other runtime source file. `getg()` is a compiler builtin
// in package runtime, so a one-liner that returns its goid field is
// the smallest possible footprint we can leave in the stdlib archive.
//
// Linkname rules (Go 1.23+) block third-party linkname into private
// runtime symbols. Exporting the function (capital G) sidesteps the
// restriction: an exported symbol is always linker-visible and pkg/q
// can pull it without runtime cooperating via go:linkname push.

const runtimePkgPath = "runtime"

const runtimeGoidStubSource = `// Code generated by the q preprocessor. DO NOT EDIT.

package runtime

import _ "unsafe"

// GoroutineID returns the current goroutine's runtime ID (g.goid).
// Injected by q's toolexec preprocessor.
//
// The single-arg //go:linkname marks this symbol as intentionally
// linker-exposed by its own name, satisfying Go 1.23+'s requirement
// that third-party linkname pulls into runtime can only target
// symbols runtime has explicitly declared as such.
//
//go:linkname GoroutineID
func GoroutineID() uint64 {
	return getg().goid
}
`

// planRuntimeStub appends the goid-accessor companion file to the
// runtime package's compile invocation.
func planRuntimeStub(toolArgs []string) (*Plan, error) {
	path, cleanup, err := writeTempGoFile("q-runtime-goid-*.go", []byte(runtimeGoidStubSource))
	if err != nil {
		return nil, err
	}
	newArgs := append(append([]string(nil), toolArgs...), path)
	return &Plan{NewArgs: newArgs, Cleanup: cleanup}, nil
}
